/*
Copyright (c) 2021, Joao Santos
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree.
*/

using System;
using System.Collections;

using UnityEngine;
using UnityEngine.Events;

using JoaoSant0s.ServicePackage.General;

namespace JoaoSant0s.ServicePackage.Routine
{
    public enum WaitRoutineOptions
    {
        None,
        SkipFirstFrame,
        EndOfFrame,
        FixedUpdate
    }

    public class RoutineService : Service
    {

        #region Override Methods

        public override void OnInit() { }

        #endregion


        #region Public Methods

        /// <summary>
        /// Create a coroutine after a specific time to execute a action
        /// </summary>
        /// <param name="delayTime"> delay to execute the action </param>
        /// <param name="action"> the action to execute after the time </param>
        /// <param name="beginOption"> the optional extra delay before the routine start </param>
        public Coroutine WaitTimeThenDo(float delayTime, UnityAction action, WaitRoutineOptions beginOption = WaitRoutineOptions.None)
        {
            return StartCoroutine(WaitTimeThenDoRoutine(delayTime, action, beginOption));
        }

        /// <summary>
        /// Create a coroutine that execute a action after a condition be true
        /// </summary>
        /// <param name="checkCondition"> the condition to be checked </param>
        /// <param name="action"> the action to execute after the time </param>
        /// <param name="beginOption"> the optional extra delay before the routine start </param>
        public Coroutine WaitUntilThenDo(Func<bool> checkCondition, UnityAction action, WaitRoutineOptions beginOption = WaitRoutineOptions.None)
        {
            return StartCoroutine(WaitUntilThenDoRoutine(checkCondition, action, beginOption));
        }

        /// <summary>
        /// Stop a condition genereted
        /// </summary>
        /// <param name="coroutine"> the coroutine generated by this service </param>
        public void Stop(Coroutine coroutine)
        {
            StopCoroutine(coroutine);
        }

        #endregion

        #region Private Methods
        private IEnumerator WaitTimeThenDoRoutine(float delayTime, UnityAction action, WaitRoutineOptions beginOption)
        {
            if (beginOption != WaitRoutineOptions.None) yield return OptionRoutine(beginOption);

            yield return new WaitForSeconds(delayTime);
            action();
        }

        private IEnumerator WaitUntilThenDoRoutine(Func<bool> checkCondition, UnityAction action, WaitRoutineOptions beginOption)
        {
            if (beginOption != WaitRoutineOptions.None) yield return OptionRoutine(beginOption);

            yield return new WaitUntil(checkCondition);
            action();
        }

        private IEnumerator OptionRoutine(WaitRoutineOptions option)
        {
            if (option == WaitRoutineOptions.EndOfFrame)
            {
                yield return new WaitForEndOfFrame();
            }
            else if (option == WaitRoutineOptions.FixedUpdate)
            {
                yield return new WaitForFixedUpdate();
            }
            else
            {
                yield return null;
            }
        }

        #endregion
    }
}